name: Not Just Art
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8924731
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Not Just Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#FF00FC'
    - '#020202'
    - '#5C5C5C'
    - '#BEBEBE'
  brandStrength: 0.8422939
  lightness: 0.5967742
  saturation: 1
  rhythmicContrast: 0.5519713
purpose: []
