layout_spectrum: 0.8697954
typography_spectrum: 0.981319
color:
  saturation: 0.8101151
  lightness: 0.3897183
  brandStrength: 0.2857852
  rhythmicContrast: 0.6498834
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Not Just Art
